"""create_tables_for_user_and_auth_modules

Revision ID: d008de801ef0
Revises:
Create Date: 2026-09-16 02:35:08.311096

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d008de801ef0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "permissions",
    sa.PrimaryKeyConstraint("id"),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    comment="Permission definition table. Each permission is associated with a role.",
  )
  op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
  op.create_table(
    "roles",
    sa.PrimaryKeyConstraint("id"),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(length=50), nullable=False),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    comment="Role definition table. Each role can have multiple users and permissions.",
  )
  op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
  op.create_table(
    "users",
    sa.PrimaryKeyConstraint("id"),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("uuid", sa.String(length=255), nullable=False),
    sa.Column("email", sa.String(length=255), nullable=False),
    sa.Column("password", sa.String(length=255), nullable=False),
    sa.Column("first_name", sa.String(length=255), nullable=True),
    sa.Column("last_name", sa.String(length=255), nullable=True),
    sa.Column("address", sa.String(length=255), nullable=True),
    sa.Column("phone_number", sa.String(length=255), nullable=True),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    comment="User definition table. Each user can have multiple roles.",
  )
  op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
  op.create_index(op.f("ix_users_uuid"), "users", ["uuid"], unique=True)
  op.create_table(
    "devices",
    sa.PrimaryKeyConstraint("id"),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("client_device_id", sa.String(length=255), nullable=False),
    sa.Column("device_type", sa.String(length=50), nullable=True),
    sa.Column("os", sa.String(length=50), nullable=True),
    sa.Column("browser", sa.String(length=50), nullable=True),
    sa.Column("ip_address", sa.String(length=45), nullable=True),
    sa.Column("latitude", sa.Float(), nullable=True),
    sa.Column("longitude", sa.Float(), nullable=True),
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    comment="Logs unique user devices and session origins.",
  )
  op.create_index(
    op.f("ix_devices_client_device_id"), "devices", ["client_device_id"], unique=False
  )
  op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
  op.create_table(
    "one_time_pins",
    sa.PrimaryKeyConstraint("id"),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("pin_hash", sa.String(length=64), nullable=False),
    sa.Column("purpose", sa.String(length=30), nullable=False),
    sa.Column("expires_at", sa.DateTime(), nullable=False),
    sa.Column("is_revoked", sa.Boolean(), nullable=False),
    sa.Column("is_used", sa.Boolean(), nullable=False),
    sa.Column("attempts", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    comment="Logs and manages OTPs for authentication/MFA.",
  )
  op.create_index(
    op.f("ix_one_time_pins_expires_at"), "one_time_pins", ["expires_at"], unique=False
  )
  op.create_index(op.f("ix_one_time_pins_pin_hash"), "one_time_pins", ["pin_hash"], unique=False)
  op.create_index(op.f("ix_one_time_pins_user_id"), "one_time_pins", ["user_id"], unique=False)
  op.create_table(
    "role_permissions",
    sa.PrimaryKeyConstraint("id"),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("role_id", sa.Integer(), nullable=False),
    sa.Column("permission_id", sa.Integer(), nullable=False),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
    comment="Junction table connecting Roles and Permissions.",
  )
  op.create_index(
    op.f("ix_role_permissions_permission_id"), "role_permissions", ["permission_id"], unique=False
  )
  op.create_index(
    op.f("ix_role_permissions_role_id"), "role_permissions", ["role_id"], unique=False
  )
  op.create_table(
    "user_roles",
    sa.PrimaryKeyConstraint("id"),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("role_id", sa.Integer(), nullable=False),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    comment="Junction table connecting Users and Roles.",
  )
  op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
  op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
  op.create_table(
    "auth_tokens",
    sa.PrimaryKeyConstraint("id"),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("token_hash", sa.String(length=64), nullable=False),
    sa.Column("token_type", sa.String(length=20), nullable=False),
    sa.Column("expires_at", sa.DateTime(), nullable=False),
    sa.Column("is_revoked", sa.Boolean(), nullable=False),
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.Column("device_id", sa.BigInteger(), nullable=True),
    sa.Column(
      "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column(
      "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    ),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
  )
  op.create_index(op.f("ix_auth_tokens_expires_at"), "auth_tokens", ["expires_at"], unique=False)
  op.create_index(op.f("ix_auth_tokens_is_revoked"), "auth_tokens", ["is_revoked"], unique=False)
  op.create_index(op.f("ix_auth_tokens_token_hash"), "auth_tokens", ["token_hash"], unique=True)
  op.create_index(op.f("ix_auth_tokens_user_id"), "auth_tokens", ["user_id"], unique=False)
  op.create_index(
    "ix_auth_tokens_user_revoked", "auth_tokens", ["user_id", "is_revoked"], unique=False
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index("ix_auth_tokens_user_revoked", table_name="auth_tokens")
  op.drop_index(op.f("ix_auth_tokens_user_id"), table_name="auth_tokens")
  op.drop_index(op.f("ix_auth_tokens_token_hash"), table_name="auth_tokens")
  op.drop_index(op.f("ix_auth_tokens_is_revoked"), table_name="auth_tokens")
  op.drop_index(op.f("ix_auth_tokens_expires_at"), table_name="auth_tokens")
  op.drop_table("auth_tokens")
  op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
  op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
  op.drop_table("user_roles")
  op.drop_index(op.f("ix_role_permissions_role_id"), table_name="role_permissions")
  op.drop_index(op.f("ix_role_permissions_permission_id"), table_name="role_permissions")
  op.drop_table("role_permissions")
  op.drop_index(op.f("ix_one_time_pins_user_id"), table_name="one_time_pins")
  op.drop_index(op.f("ix_one_time_pins_pin_hash"), table_name="one_time_pins")
  op.drop_index(op.f("ix_one_time_pins_expires_at"), table_name="one_time_pins")
  op.drop_table("one_time_pins")
  op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
  op.drop_index(op.f("ix_devices_client_device_id"), table_name="devices")
  op.drop_table("devices")
  op.drop_index(op.f("ix_users_uuid"), table_name="users")
  op.drop_index(op.f("ix_users_email"), table_name="users")
  op.drop_table("users")
  op.drop_index(op.f("ix_roles_name"), table_name="roles")
  op.drop_table("roles")
  op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
  op.drop_table("permissions")
  # ### end Alembic commands ###
