"""updated_auth_table_token_hash

Revision ID: 444a142e4f10
Revises: b5c4cccd26fc
Create Date: 2026-09-18 07:25:31.358429

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "444a142e4f10"
down_revision: str | None = "b5c4cccd26fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "auth_tokens",
    "token_type",
    existing_type=sa.VARCHAR(length=20),
    type_=sa.String(length=50),
    existing_nullable=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "auth_tokens",
    "token_type",
    existing_type=sa.String(length=50),
    type_=sa.VARCHAR(length=20),
    existing_nullable=False,
  )
  # ### end Alembic commands ###
