"""updated_auth_tokens_table

Revision ID: f8eda6450e0c
Revises: d008de801ef0
Create Date: 2026-09-18 06:54:13.030908

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8eda6450e0c"
down_revision: str | None = "d008de801ef0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "auth_tokens",
    "token_hash",
    existing_type=sa.VARCHAR(length=64),
    type_=sa.String(length=500),
    existing_nullable=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "auth_tokens",
    "token_hash",
    existing_type=sa.String(length=500),
    type_=sa.VARCHAR(length=64),
    existing_nullable=False,
  )
  # ### end Alembic commands ###
