"""update_auth_table_toke_type_column

Revision ID: b5c4cccd26fc
Revises: f8eda6450e0c
Create Date: 2026-09-18 07:13:04.371918

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b5c4cccd26fc"
down_revision: str | None = "f8eda6450e0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###
