"""updated_auth_token_table_add_family_id_column

Revision ID: 4b9311e13704
Revises: 444a142e4f10
Create Date: 2026-09-18 07:33:45.696916

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b9311e13704"
down_revision: str | None = "444a142e4f10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("auth_tokens", sa.Column("family_id", sa.String(length=255), nullable=False))

  # Create the Enum type in PostgreSQL before altering the column
  token_type_enum = sa.Enum(
    "ACCESS", "REFRESH", "CONFIRM_EMAIL", "PASSWORD_UPDATE", name="tokentype"
  )
  token_type_enum.create(op.get_bind(), checkfirst=True)

  # Use execute to run a raw SQL command for the type cast with USING clause
  op.execute(
    "ALTER TABLE auth_tokens ALTER COLUMN token_type TYPE tokentype USING token_type::tokentype"
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "auth_tokens",
    "token_type",
    existing_type=sa.Enum(
      "ACCESS", "REFRESH", "CONFIRM_EMAIL", "PASSWORD_UPDATE", name="tokentype"
    ),
    type_=sa.VARCHAR(length=50),
    existing_nullable=False,
  )
  op.drop_column("auth_tokens", "family_id")
  # ### end Alembic commands ###
