"""update_token_table_token_hash_length

Revision ID: 12aad0f1ca10
Revises: 4b9311e13704
Create Date: 2026-09-18 07:45:04.282389

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12aad0f1ca10"
down_revision: str | None = "4b9311e13704"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "auth_tokens",
    "token_hash",
    existing_type=sa.VARCHAR(length=500),
    type_=sa.String(length=1000),
    existing_nullable=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "auth_tokens",
    "token_hash",
    existing_type=sa.String(length=1000),
    type_=sa.VARCHAR(length=500),
    existing_nullable=False,
  )
  # ### end Alembic commands ###
